# cmd: conda build .  -c auto-mech -c psi4 -c rdkit -c openbabel -c conda-forge
package:
    name: autoio-base
    version: "0.7.5"

source:
    path: .

requirements:
    host:
        - python=3.7
    run:
        - gfortran_linux-64  # [linux]
        - python=3.7
        - numpy
        - scipy
        - pyyaml
        - mako
        - networkx
        - matplotlib
        - pytest
        - pytest-cov
        - future
        - flake8
        - pylint
        - psi4::psi4
        - rdkit::rdkit
        - openbabel::openbabel
        - conda-forge::qcelemental
