version: 2
jobs:
    test-autoio-interfaces:
        docker:
            - image: continuumio/miniconda3
        steps:
            - checkout  # checkout the code
            - run: 
                name: Create conda environment
                command: |
                    apt-get update --yes
                    apt-get install --yes libxrender-dev build-essential
                    conda env create -f autoio-interfaces/environment.yml
            - run:
                name: Build/install autoio-interfaces
                command: |
                    source activate autoio-interfaces-env
                    cd autoio-interfaces
                    python setup.py install
            - run:
                name: Test chemkin_io
                command: |
                    cd autoio-interfaces/chemkin_io
                    source activate autoio-interfaces-env
                    pytest . -v --disable-pytest-warnings --cov=chemkin_io --pyargs chemkin_io --cov-report=html
                    coverage report
            - run:
               name: Test intder_io
               command: |
                   cd autoio-interfaces/intder_io
                   source activate autoio-interfaces-env
                   pytest . -v --disable-pytest-warnings --cov=intder_io --pyargs intder_io --cov-report=html
                   coverage report
            - run:
                name: Test pac99_io
                command: |
                    cd autoio-interfaces/pac99_io
                    source activate autoio-interfaces-env
                    pytest . -v --disable-pytest-warnings --cov=pac99_io --pyargs pac99_io --cov-report=html
                    coverage report
            - run:
                name: Test projrot_io
                command: |
                    cd autoio-interfaces/projrot_io
                    source activate autoio-interfaces-env
                    pytest . -v --disable-pytest-warnings --cov=projrot_io --pyargs projrot_io --cov-report=html
                    coverage report
            - run:
                name: Test polyrate_io
                command: |
                    cd autoio-interfaces/polyrate_io
                    source activate autoio-interfaces-env
                    pytest . -v --disable-pytest-warnings --cov=polyrate_io --pyargs polyrate_io --cov-report=html
                    coverage report
            - run:
                name: Test thermp_io
                command: |
                    cd autoio-interfaces/thermp_io
                    source activate autoio-interfaces-env
                    pytest . -v --disable-pytest-warnings --cov=thermp_io --pyargs thermp_io --cov-report=html
                    coverage report
            - run:
                name: Test varecof_io
                command: |
                    cd autoio-interfaces/varecof_io
                    source activate autoio-interfaces-env
                    pytest . -v --disable-pytest-warnings --cov=varecof_io --pyargs varecof_io --cov-report=html
                    coverage report
            - run:
                name: Test onedmin_io
                command: |
                    cd autoio-interfaces/onedmin_io
                    source activate autoio-interfaces-env
                    pytest . -v --disable-pytest-warnings --cov=onedmin_io --pyargs onedmin_io --cov-report=html
                    coverage report
            - run:
                name: Test mess_io
                command: |
                    cd autoio-interfaces/mess_io
                    source activate autoio-interfaces-env
                    pytest . -v --disable-pytest-warnings --cov=mess_io --pyargs mess_io --cov-report=html
                    coverage report
            - run:
                name: Test autorun
                command: |
                    cd autoio-interfaces/autorun
                    source activate autoio-interfaces-env
                    pytest . -v --disable-pytest-warnings --cov=autorun --pyargs autorun --cov-report=html
                    coverage report
            - run:
                name: Test elstruct
                command: |
                    cd autoio-interfaces/elstruct
                    source activate autoio-interfaces-env
                    pytest -v --cov=elstruct . --cov-report=html
                    coverage report
            - run:
                name: Test autoio-interfaces_pylint
                command: |
                    cd autoio-interfaces
                    source activate autoio-interfaces-env
                    flake8 --exit-zero ../autoio-interfaces
                    pylint --rcfile=../.pylintrc $(git ls-files '*.py')
            - store_artifacts:
                    path: autoio-interfaces/chemkin_io/htmlcov
            - store_artifacts:
                    path: autoio-interfaces/intder_io/htmlcov
            - store_artifacts:
                    path: autoio-interfaces/pac99_io/htmlcov
            - store_artifacts:
                    path: autoio-interfaces/projrot_io/htmlcov
            - store_artifacts:
                    path: autoio-interfaces/polyrate_io/htmlcov
            - store_artifacts:
                    path: autoio-interfaces/thermp_io/htmlcov
            - store_artifacts:
                    path: autoio-interfaces/varecof_io/htmlcov
            - store_artifacts:
                    path: autoio-interfaces/onedmin_io/htmlcov
            - store_artifacts:
                    path: autoio-interfaces/mess_io/htmlcov
            - store_artifacts:
                    path: autoio-interfaces/elstruct/htmlcov
            - store_artifacts:
                    path: autoio-interfaces/autorun/htmlcov
    test-autoio-base:
        docker:
            - image: continuumio/miniconda3
        steps:
            - checkout  # checkout the code
            - run: 
                name: Create conda environment
                command: |
                    apt-get update --yes
                    apt-get install --yes libxrender-dev build-essential
                    conda env create -f autoio-base/environment.yml
            - run:
                name: Build/install autoio-base
                command: |
                    source activate autoio-base-env
                    cd autoio-base
                    python setup.py install
            - run:
                name: Test autoparse
                command: |
                    source activate autoio-base-env
                    cd autoio-base/autoparse
                    pytest . -v --disable-pytest-warnings --cov=autoparse  --pyargs autoparse --cov-report=html
                    coverage report
            - run:
                name: Test autoread
                command: |
                    cd autoio-base/autoread
                    source activate autoio-base-env
                    pytest . -v --disable-pytest-warnings --cov=autoread --pyargs autoread --cov-report=html
                    coverage report
            - run:
                name: Test autowrite
                command: |
                    cd autoio-base/autowrite
                    source activate autoio-base-env
                    pytest . -v --disable-pytest-warnings --cov=autowrite --pyargs autowrite --cov-report=html
                    coverage report
            - run:
                name: Test ioformat
                command: |
                    cd autoio-base/ioformat
                    source activate autoio-base-env
                    pytest . -v --disable-pytest-warnings --cov=ioformat --pyargs ioformat --cov-report=html
                    coverage report
            - run:
                name: Test autoio-base_pylint
                command: |
                    cd autoio-base
                    source activate autoio-base-env
                    flake8 --exit-zero ../autoio-base
                    pylint --rcfile=../.pylintrc $(git ls-files '*.py')
            - store_artifacts:
                    path: autoio-base/autoparse/htmlcov
            - store_artifacts:
                    path: autoio-base/autoread/htmlcov
            - store_artifacts:
                    path: autoio-base/autowrite/htmlcov
            - store_artifacts:
                    path: autoio-base/ioformat/htmlcov
workflows:
    version: 2
    build-all:
        jobs:
            - test-autoio-base
            - test-autoio-interfaces
